version: "3.7"

services: 
    client: 
        container_name: bashaKoi_client
        restart: unless-stopped
        build: 
            context: ./client
            dockerfile: Dockerfile 
        ports: 
            - 3000:3000

    server: 
        container_name: bashaKoi_server
        restart: unless-stopped 
        build: 
            context: ./server 
            dockerfile: Dockerfile
        ports: 
            - 5000:5000
